const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="PendamaJayden@gmail.com"
global.location="Harare,Zimbabwe."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Africa/Harare";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029VaZypgoIyPtaodVKp61o";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029VaZypgoIyPtaodVKp61o" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "263712473551" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "263712473551";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©fuckoff²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "Jayden",

  sessionName:process.env.SESSION_ID || "SUHAIL_22_09_08_17_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTEyLFxuICAgICAgICA5MSxcbiAgICAgICAgNjYsXG4gICAgICAgIDIzOSxcbiAgICAgICAgMjMsXG4gICAgICAgIDEyMixcbiAgICAgICAgMTM4LFxuICAgICAgICAxNjIsXG4gICAgICAgIDg1LFxuICAgICAgICA1LFxuICAgICAgICAxNTAsXG4gICAgICAgIDgsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMTE1LFxuICAgICAgICAxNjQsXG4gICAgICAgIDMxLFxuICAgICAgICAyMTcsXG4gICAgICAgIDMyLFxuICAgICAgICAxMjksXG4gICAgICAgIDE0MSxcbiAgICAgICAgMjM1LFxuICAgICAgICAzNixcbiAgICAgICAgMTc4LFxuICAgICAgICAxNTAsXG4gICAgICAgIDY3LFxuICAgICAgICAyMzgsXG4gICAgICAgIDE2NyxcbiAgICAgICAgNjksXG4gICAgICAgIDE5MSxcbiAgICAgICAgMTM2LFxuICAgICAgICA0MixcbiAgICAgICAgMTA4XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDU3LFxuICAgICAgICA1NyxcbiAgICAgICAgMTc3LFxuICAgICAgICAxMyxcbiAgICAgICAgNjcsXG4gICAgICAgIDI0MyxcbiAgICAgICAgMjU1LFxuICAgICAgICAzMixcbiAgICAgICAgMTcsXG4gICAgICAgIDE5MSxcbiAgICAgICAgMTkzLFxuICAgICAgICAyNCxcbiAgICAgICAgODEsXG4gICAgICAgIDIzMSxcbiAgICAgICAgMTMsXG4gICAgICAgIDE3NSxcbiAgICAgICAgMjQ1LFxuICAgICAgICA0NyxcbiAgICAgICAgMTQ2LFxuICAgICAgICAyNTQsXG4gICAgICAgIDU2LFxuICAgICAgICA5MyxcbiAgICAgICAgMjIsXG4gICAgICAgIDIyNixcbiAgICAgICAgNjQsXG4gICAgICAgIDMyLFxuICAgICAgICAxODEsXG4gICAgICAgIDE4NSxcbiAgICAgICAgMjQsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMjE5LFxuICAgICAgICAyM1xuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTEyLFxuICAgICAgICA5NSxcbiAgICAgICAgMTk5LFxuICAgICAgICA2NyxcbiAgICAgICAgMTk1LFxuICAgICAgICAxMTQsXG4gICAgICAgIDkwLFxuICAgICAgICAxMTMsXG4gICAgICAgIDcsXG4gICAgICAgIDE5LFxuICAgICAgICAyNSxcbiAgICAgICAgNTMsXG4gICAgICAgIDIxLFxuICAgICAgICAyNTAsXG4gICAgICAgIDQxLFxuICAgICAgICAyMzgsXG4gICAgICAgIDkwLFxuICAgICAgICA5NCxcbiAgICAgICAgNSxcbiAgICAgICAgMTU0LFxuICAgICAgICA5MixcbiAgICAgICAgMjE3LFxuICAgICAgICAxNDEsXG4gICAgICAgIDQzLFxuICAgICAgICA4NixcbiAgICAgICAgMTMyLFxuICAgICAgICAxMjAsXG4gICAgICAgIDY1LFxuICAgICAgICA2MSxcbiAgICAgICAgMTkyLFxuICAgICAgICA2NyxcbiAgICAgICAgMTEwXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIyNixcbiAgICAgICAgMTk0LFxuICAgICAgICAxMzYsXG4gICAgICAgIDUwLFxuICAgICAgICAyNixcbiAgICAgICAgMTExLFxuICAgICAgICAyMTMsXG4gICAgICAgIDE3OSxcbiAgICAgICAgNixcbiAgICAgICAgMSxcbiAgICAgICAgMjcsXG4gICAgICAgIDIyOCxcbiAgICAgICAgMTQ1LFxuICAgICAgICAxMjIsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMTc1LFxuICAgICAgICAyNTUsXG4gICAgICAgIDcwLFxuICAgICAgICA3LFxuICAgICAgICA2OCxcbiAgICAgICAgMTIxLFxuICAgICAgICAyMzcsXG4gICAgICAgIDIyMSxcbiAgICAgICAgMTAzLFxuICAgICAgICAyMyxcbiAgICAgICAgNTksXG4gICAgICAgIDIxLFxuICAgICAgICAyMjYsXG4gICAgICAgIDMyLFxuICAgICAgICA3NCxcbiAgICAgICAgMTY2LFxuICAgICAgICAyOVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMCxcbiAgICAgICAgMjM4LFxuICAgICAgICAxMzEsXG4gICAgICAgIDE0MCxcbiAgICAgICAgNzAsXG4gICAgICAgIDcyLFxuICAgICAgICAxMjAsXG4gICAgICAgIDE0NSxcbiAgICAgICAgNjksXG4gICAgICAgIDY1LFxuICAgICAgICA0MSxcbiAgICAgICAgMTEyLFxuICAgICAgICAxNDksXG4gICAgICAgIDEzNSxcbiAgICAgICAgMTAyLFxuICAgICAgICAxODQsXG4gICAgICAgIDIyNixcbiAgICAgICAgMTk4LFxuICAgICAgICAxMjEsXG4gICAgICAgIDE3NixcbiAgICAgICAgNjksXG4gICAgICAgIDAsXG4gICAgICAgIDExMyxcbiAgICAgICAgMTAsXG4gICAgICAgIDIxMyxcbiAgICAgICAgNTcsXG4gICAgICAgIDIwOCxcbiAgICAgICAgODAsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMTkxLFxuICAgICAgICAzLFxuICAgICAgICAxMjVcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTgyLFxuICAgICAgICA1LFxuICAgICAgICAzOCxcbiAgICAgICAgMjI5LFxuICAgICAgICAyMTYsXG4gICAgICAgIDExMCxcbiAgICAgICAgMTczLFxuICAgICAgICAxMzEsXG4gICAgICAgIDE0NSxcbiAgICAgICAgMjUxLFxuICAgICAgICAyMDYsXG4gICAgICAgIDgsXG4gICAgICAgIDIwNixcbiAgICAgICAgMTg1LFxuICAgICAgICAxMzcsXG4gICAgICAgIDEzLFxuICAgICAgICAxNDYsXG4gICAgICAgIDQ1LFxuICAgICAgICAxNSxcbiAgICAgICAgMjAwLFxuICAgICAgICAzNCxcbiAgICAgICAgNDUsXG4gICAgICAgIDgxLFxuICAgICAgICAxMTksXG4gICAgICAgIDEwNSxcbiAgICAgICAgMTg0LFxuICAgICAgICA3MCxcbiAgICAgICAgMTkwLFxuICAgICAgICA0OCxcbiAgICAgICAgMTYsXG4gICAgICAgIDEzMixcbiAgICAgICAgNjFcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMjE2LFxuICAgICAgICAgIDE4NixcbiAgICAgICAgICAyMzAsXG4gICAgICAgICAgODksXG4gICAgICAgICAgMTMwLFxuICAgICAgICAgIDE5NixcbiAgICAgICAgICAxMTEsXG4gICAgICAgICAgMTU5LFxuICAgICAgICAgIDUzLFxuICAgICAgICAgIDIsXG4gICAgICAgICAgMTcyLFxuICAgICAgICAgIDQ1LFxuICAgICAgICAgIDEyNixcbiAgICAgICAgICAyMzYsXG4gICAgICAgICAgMTk4LFxuICAgICAgICAgIDkzLFxuICAgICAgICAgIDExOCxcbiAgICAgICAgICA5OCxcbiAgICAgICAgICAxMTAsXG4gICAgICAgICAgMTY4LFxuICAgICAgICAgIDExMCxcbiAgICAgICAgICAxNDMsXG4gICAgICAgICAgMTAsXG4gICAgICAgICAgMjUwLFxuICAgICAgICAgIDQ3LFxuICAgICAgICAgIDkzLFxuICAgICAgICAgIDU2LFxuICAgICAgICAgIDQ0LFxuICAgICAgICAgIDcxLFxuICAgICAgICAgIDIzMixcbiAgICAgICAgICA5NixcbiAgICAgICAgICA5MFxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxMjIsXG4gICAgICAgICAgMTkzLFxuICAgICAgICAgIDE0LFxuICAgICAgICAgIDE1NixcbiAgICAgICAgICAxMDIsXG4gICAgICAgICAgNDQsXG4gICAgICAgICAgOTQsXG4gICAgICAgICAgNzIsXG4gICAgICAgICAgMTUyLFxuICAgICAgICAgIDE4MixcbiAgICAgICAgICAxNCxcbiAgICAgICAgICAxMCxcbiAgICAgICAgICA3MixcbiAgICAgICAgICAzMixcbiAgICAgICAgICAxMDksXG4gICAgICAgICAgMTM2LFxuICAgICAgICAgIDc2LFxuICAgICAgICAgIDc4LFxuICAgICAgICAgIDQ0LFxuICAgICAgICAgIDI3LFxuICAgICAgICAgIDE5MixcbiAgICAgICAgICAyNDUsXG4gICAgICAgICAgMjA4LFxuICAgICAgICAgIDEsXG4gICAgICAgICAgMjQ5LFxuICAgICAgICAgIDEsXG4gICAgICAgICAgNTQsXG4gICAgICAgICAgMSxcbiAgICAgICAgICA4OSxcbiAgICAgICAgICAxNjMsXG4gICAgICAgICAgMzMsXG4gICAgICAgICAgOTJcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNTQsXG4gICAgICAgIDEzNyxcbiAgICAgICAgMTI2LFxuICAgICAgICAxNixcbiAgICAgICAgNCxcbiAgICAgICAgODIsXG4gICAgICAgIDEyNixcbiAgICAgICAgMjI2LFxuICAgICAgICAxNTUsXG4gICAgICAgIDY5LFxuICAgICAgICAxMTgsXG4gICAgICAgIDEzOSxcbiAgICAgICAgMTg3LFxuICAgICAgICAxMTMsXG4gICAgICAgIDY2LFxuICAgICAgICAxNzYsXG4gICAgICAgIDk0LFxuICAgICAgICAxNTEsXG4gICAgICAgIDIxOSxcbiAgICAgICAgMTE4LFxuICAgICAgICAyNDAsXG4gICAgICAgIDQ4LFxuICAgICAgICAxNTYsXG4gICAgICAgIDI4LFxuICAgICAgICAxOTMsXG4gICAgICAgIDkyLFxuICAgICAgICA2NCxcbiAgICAgICAgMjI4LFxuICAgICAgICAxOTYsXG4gICAgICAgIDQyLFxuICAgICAgICAyMjcsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMjUyLFxuICAgICAgICA2NSxcbiAgICAgICAgMTkzLFxuICAgICAgICAxNTYsXG4gICAgICAgIDk1LFxuICAgICAgICAxNTAsXG4gICAgICAgIDE5MyxcbiAgICAgICAgODQsXG4gICAgICAgIDg1LFxuICAgICAgICAxMTAsXG4gICAgICAgIDcsXG4gICAgICAgIDEwMSxcbiAgICAgICAgMjExLFxuICAgICAgICAxMTEsXG4gICAgICAgIDEzLFxuICAgICAgICAxMjAsXG4gICAgICAgIDExNyxcbiAgICAgICAgMjQwLFxuICAgICAgICA3NCxcbiAgICAgICAgNDcsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMjMwLFxuICAgICAgICAxNDUsXG4gICAgICAgIDg4LFxuICAgICAgICA1OCxcbiAgICAgICAgMTE1LFxuICAgICAgICA0NyxcbiAgICAgICAgMTA2LFxuICAgICAgICAyMzMsXG4gICAgICAgIDI2LFxuICAgICAgICA4MyxcbiAgICAgICAgN1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogMTA4LFxuICBcImFkdlNlY3JldEtleVwiOiBcInRjVHJCMjdPMzBWbzkwbzBmenpJK25TcktiTHNPanBJZW4xU0Y1bVM5T1k9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiMjMzNTk5NjYyODg5QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCJGRjNBMEUyRkE3RjFCOEU1QjVGNUJDMTdDMkNFQjY5MlwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjM5MzI1ODlcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAxLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiYlN2RXI3cGRRQTY2RXJ1V3V4RVliQVwiLFxuICBcInBob25lSWRcIjogXCI3ODRlMjlhYy03MmY1LTQ5ZjktYmZjZC1jNTQ5OWNmOGQxZWJcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMjM1LFxuICAgICAgMTg0LFxuICAgICAgMTc3LFxuICAgICAgMTUyLFxuICAgICAgNzAsXG4gICAgICAxMTgsXG4gICAgICAyMzAsXG4gICAgICAyMzAsXG4gICAgICAxMDEsXG4gICAgICA0MSxcbiAgICAgIDEwMCxcbiAgICAgIDE0NixcbiAgICAgIDE4NSxcbiAgICAgIDIwNSxcbiAgICAgIDIxNixcbiAgICAgIDExMyxcbiAgICAgIDIyNCxcbiAgICAgIDE1OSxcbiAgICAgIDEwLFxuICAgICAgMTMyXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogdHJ1ZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDQyLFxuICAgICAgMTkwLFxuICAgICAgMjM4LFxuICAgICAgMjM3LFxuICAgICAgMTgxLFxuICAgICAgMjI1LFxuICAgICAgMTc2LFxuICAgICAgMjUsXG4gICAgICAxMDYsXG4gICAgICAxNzUsXG4gICAgICA0NCxcbiAgICAgIDYxLFxuICAgICAgMjI3LFxuICAgICAgMTAyLFxuICAgICAgMjAxLFxuICAgICAgMTExLFxuICAgICAgMTIwLFxuICAgICAgMTg2LFxuICAgICAgNixcbiAgICAgIDE3OFxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwicGFpcmluZ0NvZGVcIjogXCJRTlo4V0xGWVwiLFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiMjMzNTk5NjYyODg5OjQ2QHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJuYW1lXCI6IFwiREFSSyBaRVJPQ09PTFwiLFxuICAgIFwibGlkXCI6IFwiMTI0MjkyNTI4Mzg2MjEwOjQ2QGxpZFwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ0ptWGd1WUZFS1cvaExZR0dBRWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwieUlySk54UHdJdjNGdld0Vld6dEQwMXZUS3pjZ2RSaUg2R0tLdGd3QzlVbz1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJHbldMNnNhYjhjZ0IvKy9SVWswYWh6RTkwV2NkZmJPSzVNRlQrYmVEU1hKcG90VmVPSWdRcEhsR09XNnk3VDlZNHdrb0szOUVkSmt4REpMV1V4ZGxDUT09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJiTHJleFc2c05zWFZDV1M1Q2xYY3A2YlJjaXlkQ1VvZ3FsamtmRTRFalpxN05FRi93NU5ZeVJsbCtDYm02aWhNWXhvWlhrbnErWG1XMmlZV1FvNStDdz09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCIyMzM1OTk2NjI4ODk6NDZAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAyMDAsXG4gICAgICAgICAgMTM4LFxuICAgICAgICAgIDIwMSxcbiAgICAgICAgICA1NSxcbiAgICAgICAgICAxOSxcbiAgICAgICAgICAyNDAsXG4gICAgICAgICAgMzQsXG4gICAgICAgICAgMjUzLFxuICAgICAgICAgIDE5NyxcbiAgICAgICAgICAxODksXG4gICAgICAgICAgMTA3LFxuICAgICAgICAgIDg1LFxuICAgICAgICAgIDkxLFxuICAgICAgICAgIDU5LFxuICAgICAgICAgIDY3LFxuICAgICAgICAgIDIxMSxcbiAgICAgICAgICA5MSxcbiAgICAgICAgICAyMTEsXG4gICAgICAgICAgNDMsXG4gICAgICAgICAgNTUsXG4gICAgICAgICAgMzIsXG4gICAgICAgICAgMTE3LFxuICAgICAgICAgIDI0LFxuICAgICAgICAgIDEzNSxcbiAgICAgICAgICAyMzIsXG4gICAgICAgICAgOTgsXG4gICAgICAgICAgMTM4LFxuICAgICAgICAgIDE4MixcbiAgICAgICAgICAxMixcbiAgICAgICAgICAyLFxuICAgICAgICAgIDI0NSxcbiAgICAgICAgICA3NFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwic21iYVwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzIzOTMyNTg1LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBRktjXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFGS2MuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJpU3Rlc0NLQnZ1b2MyeCtWVUNtMUlKb1oxdE5icjJzKzBZUmhjY1FrMmM0PVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjE1NTYxMjI1MjEsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTcyMzkzMjU4OTMwOVwifSIKfQ==",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "public",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "ZEROCOOL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
